<!doctype html>
<html>
       <head>
              <meta charset="utf-8">
              <title>Assignment3-Idiotville</title>
              <link rel="stylesheet" href="css/styles.css">
              <link rel="stylesheet" href="css/navigation.css">
              <link rel="stylesheet" href="sss/sss.css">
	       	  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
       </head>
