<nav class="topnav">
    <ul>
        <li><a class = "<?php if($thisPage == 'home'){echo 'current';}?>" href="index.php">Home</a></li>
        <li><a class = "<?php if($thisPage == 'yuanzhuo'){echo 'current';}?>" href="student1.php">student1</a></li>
        <li><a class = "<?php if($thisPage == 'yidi'){echo 'current';}?>" href="student2.php">student2</a></li>
        <li><a class = "<?php if($thisPage == 'zhenghao'){echo 'current';}?>" href="student3.php">student3</a></li>
    </ul>
</nav>
